import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../theme/app_theme.dart';
import '../services/database_service.dart';
import '../utils/site_time_helper.dart';

class WorkerDetailPage extends StatefulWidget { final Map<String, dynamic> worker; const WorkerDetailPage({super.key, required this.worker}); @override State<WorkerDetailPage> createState() => _WorkerDetailPageState(); }

class _WorkerDetailPageState extends State<WorkerDetailPage> {
  final DatabaseService _db = DatabaseService();
  List<Map<String, dynamic>> _payments = []; List<Map<String, dynamic>> _attendanceRecords = [];
  Map<String, dynamic> _attendanceStats = {'present':0,'absent':0,'leave':0,'overtime_hours':0.0}; double _totalPaid = 0; bool _isLoading = true; DateTime _selectedMonth = DateTime.now();
  Map<String, dynamic> _cumulativeStats = {'present':0,'absent':0,'leave':0,'overtime_hours':0.0}; double _cumulativeTotalPaid = 0;

  int get _workerId => widget.worker['id'] as int;
  double get _dailyWage => (widget.worker['daily_wage'] as num?)?.toDouble() ?? 0;
  double get _overtimeRate { final r = (widget.worker['overtime_rate'] as num?)?.toDouble(); return r ?? (_dailyWage / 8); }
  String get _monthStart => DateTime(_selectedMonth.year, _selectedMonth.month, 1).toIso8601String().split('T').first;
  String get _monthEnd => DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0).toIso8601String().split('T').first;

  double get _totalSalary { final p = (_attendanceStats['present'] as num?)?.toInt() ?? 0; final o = (_attendanceStats['overtime_hours'] as num?)?.toDouble() ?? 0; return p * _dailyWage + o * _overtimeRate; }
  double get _owedSalary => _totalSalary - _totalPaid;
  double get _cumulativeSalary { final p = (_cumulativeStats['present'] as num?)?.toInt() ?? 0; final o = (_cumulativeStats['overtime_hours'] as num?)?.toDouble() ?? 0; return p * _dailyWage + o * _overtimeRate; }
  double get _cumulativeOwed => _cumulativeSalary - _cumulativeTotalPaid;

  Set<String> get _presentDates => _attendanceRecords.where((r) => r['is_present'] == 1).map((r) => r['date'] as String).toSet();
  Set<String> get _absentDates => _attendanceRecords.where((r) => r['is_present'] == 0).map((r) => r['date'] as String).toSet();
  Set<String> get _leaveDates => _attendanceRecords.where((r) => r['is_present'] == 2).map((r) => r['date'] as String).toSet();

  @override void initState() { super.initState(); _loadData(); }
  Future<void> _loadData() async { setState(() => _isLoading = true); try { final r = await Future.wait([_db.getAttendanceStats(_workerId, _monthStart, _monthEnd), _db.getAttendanceByWorker(_workerId, _monthStart, _monthEnd), _db.getPaymentsByWorker(_workerId), _db.getTotalPaymentsByWorker(_workerId), _db.getCumulativeAttendanceStats(_workerId)]); setState(() { _attendanceStats=r[0] as Map<String, dynamic>; _attendanceRecords=r[1] as List<Map<String, dynamic>>; _payments=r[2] as List<Map<String, dynamic>>; _totalPaid=r[3] as double; _cumulativeStats=r[4] as Map<String, dynamic>; _cumulativeTotalPaid=r[3] as double; _isLoading=false; }); } catch (e) { setState(() => _isLoading = false); if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('加载失败: $e'), backgroundColor: Colors.red)); } }

  @override Widget build(BuildContext ctx) => Scaffold(appBar: AppBar(title: Text(widget.worker['name'] ?? ''), actions: [IconButton(icon: const Icon(Icons.calendar_month), onPressed: _selectMonth), IconButton(icon: const Icon(Icons.delete), onPressed: _deleteWorker)]), body: _isLoading ? const Center(child: CircularProgressIndicator()) : SingleChildScrollView(child: Column(children: [_header(),_cum(),_monthSel(),_cal(),_tl(),_pmts(), const SizedBox(height:100)])), floatingActionButton: FloatingActionButton.extended(onPressed: () => _showPay(ctx), icon: const Icon(Icons.payment), label: const Text('记录发薪')));

  Widget _header() => Container(width:double.infinity, padding:const EdgeInsets.all(20), decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppTheme.primaryColor,AppTheme.primaryLight]), borderRadius:const BorderRadius.only(bottomLeft:Radius.circular(24),bottomRight:Radius.circular(24))), child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.center, children:[CircleAvatar(radius:32,backgroundColor:Colors.white, child:Text((widget.worker['name'] as String?)?.isNotEmpty==true?widget.worker['name'].substring(0,1):'?', style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold,color:AppTheme.primaryColor))), const SizedBox(width:16), Column(crossAxisAlignment:CrossAxisAlignment.start, children:[Text(widget.worker['name']??'', style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold,color:Colors.white)), const SizedBox(height:4), Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:4), decoration:BoxDecoration(color:Colors.white.withOpacity(0.2), borderRadius:BorderRadius.circular(12)), child:Text('${widget.worker['work_type']??''} · ${_dailyWage.toStringAsFixed(0)}元/天 · OT ${_overtimeRate.toStringAsFixed(0)}/h', style:const TextStyle(fontSize:12,color:Colors.white)))])]), const SizedBox(height:16), Row(mainAxisAlignment:MainAxisAlignment.spaceAround, children:[_hi('出勤','${_attendanceStats['present']}','天',Colors.green),_hi('缺勤','${_attendanceStats['absent']}','天',Colors.red),_hi('请假','${_attendanceStats['leave']}','天',Colors.orange),_hi('欠款','¥${_owedSalary.toStringAsFixed(0)}','',_owedSalary>0?Colors.amber:Colors.green)])]));
  Widget _hi(String l,String v,String u,Color c) => Column(children:[Row(crossAxisAlignment:CrossAxisAlignment.end, children:[Text(v,style:TextStyle(fontSize:20,fontWeight:FontWeight.bold,color:c)),if(u.isNotEmpty)Padding(padding:const EdgeInsets.only(bottom:2),child:Text(u,style:TextStyle(fontSize:10,color:c)))]),const SizedBox(height:2),Text(l,style:TextStyle(fontSize:11,color:Colors.white.withOpacity(0.8)))]);

  Widget _cum() { final cp=(_cumulativeStats['present'] as num?)?.toInt()??0; final co=(_cumulativeStats['overtime_hours'] as num?)?.toDouble()??0; return Container(margin:const EdgeInsets.fromLTRB(16,16,16,0),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:AppTheme.primaryColor.withOpacity(0.15)),boxShadow:[BoxShadow(color:AppTheme.primaryColor.withOpacity(0.06),blurRadius:12,offset:const Offset(0,4))]),child:Column(children:[Row(children:[Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:AppTheme.primaryColor.withOpacity(0.08),borderRadius:BorderRadius.circular(6)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.summarize,size:14,color:AppTheme.primaryColor),const SizedBox(width:4),const Text('累计总览',style:TextStyle(fontSize:13,fontWeight:FontWeight.w600,color:AppTheme.primaryColor))])),const Spacer(),Text('开工至今',style:TextStyle(fontSize:11,color:Colors.grey[400]))]),const SizedBox(height:14),Row(children:[_cs('出勤','$cp','天',Colors.green),_cd(),_cs('加班',co.toStringAsFixed(1),'h',Colors.orange),_cd(),_cs('应发','¥${_cumulativeSalary.toStringAsFixed(0)}','',Colors.blue),_cd(),_cs('已付','¥${_cumulativeTotalPaid.toStringAsFixed(0)}','',const Color(0xFF2E7D32)),_cd(),_cs('欠款','¥${_cumulativeOwed.toStringAsFixed(0)}','',_cumulativeOwed>0?const Color(0xFFD32F2F):const Color(0xFF2E7D32))])])); }
  Widget _cs(String l,String v,String u,Color c) => Expanded(child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Flexible(child:Text(v,textAlign:TextAlign.center,style:TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:c),overflow:TextOverflow.ellipsis)),if(u.isNotEmpty)Padding(padding:const EdgeInsets.only(bottom:1,left:1),child:Text(u,style:TextStyle(fontSize:10,color:c)))]),const SizedBox(height:4),Text(l,style:TextStyle(fontSize:11,color:Colors.grey[500]))]));
  Widget _cd() => Container(width:1,height:30,color:Colors.grey[200]);

  Widget _monthSel() => Padding(padding:const EdgeInsets.all(16),child:GestureDetector(onTap:_selectMonth,child:Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:12),decoration:BoxDecoration(color:AppTheme.primaryColor.withOpacity(0.1),borderRadius:BorderRadius.circular(12)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.calendar_today,color:AppTheme.primaryColor,size:18),const SizedBox(width:8),Text('${_selectedMonth.year}年${_selectedMonth.month}月',style:TextStyle(fontSize:16,fontWeight:FontWeight.w500,color:AppTheme.primaryColor)),const SizedBox(width:4),Icon(Icons.arrow_drop_down,color:AppTheme.primaryColor)]))));
  Future<void> _selectMonth() async { final p=await showDatePicker(context:context,initialDate:_selectedMonth,firstDate:DateTime(2020),lastDate:DateTime.now().add(const Duration(days:365)),locale:const Locale('zh','CN'),initialDatePickerMode:DatePickerMode.year); if(p!=null){setState(()=>_selectedMonth=p);_loadData();} }

  Widget _cal() => Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('出勤日历',style:TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:AppTheme.textPrimary)),Row(children:[_lg(Colors.green,'出勤'),const SizedBox(width:12),_lg(Colors.red,'缺勤'),const SizedBox(width:12),_lg(Colors.orange,'请假')])]),const SizedBox(height:16),_grid()]))));
  Widget _lg(Color c,String l)=>Row(children:[Container(width:8,height:8,decoration:BoxDecoration(color:c,shape:BoxShape.circle)),const SizedBox(width:4),Text(l,style:TextStyle(fontSize:11,color:Colors.grey[600]))]);
  Widget _grid() { final f=DateTime(_selectedMonth.year,_selectedMonth.month,1),l=DateTime(_selectedMonth.year,_selectedMonth.month+1,0); final sw=f.weekday%7; final ds=<Widget>[]; for(var i=0;i<sw;i++)ds.add(const SizedBox()); for(var d=1;d<=l.day;d++){ final dt=DateTime(_selectedMonth.year,_selectedMonth.month,d); final ds2=dt.toIso8601String().split('T').first; final ip=_presentDates.contains(ds2),ia=_absentDates.contains(ds2),il=_leaveDates.contains(ds2),it=SiteTimeHelper.isSameDay(dt,DateTime.now()),iff=dt.isAfter(DateTime.now()); ds.add(Container(margin:const EdgeInsets.all(2),decoration:BoxDecoration(color:ip?Colors.green.withOpacity(0.2):ia?Colors.red.withOpacity(0.2):il?Colors.orange.withOpacity(0.2):null,borderRadius:BorderRadius.circular(8),border:it?Border.all(color:AppTheme.primaryColor,width:2):null),child:Stack(alignment:Alignment.center,children:[Text('$d',style:TextStyle(fontSize:12,fontWeight:it?FontWeight.bold:FontWeight.normal,color:iff?Colors.grey[300]:ip?Colors.green[700]:ia?Colors.red[700]:il?Colors.orange[700]:AppTheme.textPrimary)),if(ip||ia||il)Positioned(bottom:2,child:Container(width:4,height:4,decoration:BoxDecoration(color:ip?Colors.green:ia?Colors.red:Colors.orange,shape:BoxShape.circle)))]))); } return Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:['日','一','二','三','四','五','六'].map((x)=>SizedBox(width:36,child:Center(child:Text(x,style:TextStyle(fontSize:11,color:Colors.grey[500],fontWeight:FontWeight.w500))))).toList()),const SizedBox(height:8),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:7,mainAxisSpacing:2,crossAxisSpacing:2,childAspectRatio:1,children:ds)]); }

  Widget _tl() { final its=<Map<String,dynamic>>[]; for(var r in _attendanceRecords.where((r)=>r['is_present']==1))its.add({'type':'work','date':r['date'],'amount':_dailyWage,'description':'干活挣钱'}); for(var p in _payments)its.add({'type':'payment','date':p['date'],'amount':p['amount'],'description':p['note']??'发薪记录'}); its.sort((a,b)=>(b['date'] as String).compareTo(a['date'] as String)); return Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('财务流水线',style:TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:AppTheme.textPrimary)),const SizedBox(height:12),its.isEmpty?Card(child:Padding(padding:const EdgeInsets.all(32),child:Center(child:Column(children:[Icon(Icons.timeline,size:48,color:Colors.grey[300]),const SizedBox(height:8),Text('暂无记录',style:TextStyle(color:Colors.grey[500]))])))):Card(child:Column(children:its.take(10).map((it){final last=it==its.take(10).last;final iw=it['type']=='work';return Column(children:[_tli(it,iw),if(!last)const Divider(height:1,indent:60)]);}).toList()))])); }
  Widget _tli(Map<String,dynamic> it,bool iw){final a=(it['amount'] as num?)?.toDouble()??0;return Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(width:40,height:40,decoration:BoxDecoration(color:iw?Colors.green.withOpacity(0.1):Colors.blue.withOpacity(0.1),shape:BoxShape.circle),child:Icon(iw?Icons.work:Icons.payment,color:iw?Colors.green:Colors.blue,size:20)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(it['description']??'',style:const TextStyle(fontSize:14,fontWeight:FontWeight.w500,color:AppTheme.textPrimary)),const SizedBox(height:2),Text(it['date']??'',style:const TextStyle(fontSize:12,color:Colors.grey))])),Text(iw?'+¥${a.toStringAsFixed(0)}':'-¥${a.toStringAsFixed(0)}',style:TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:iw?Colors.green:Colors.blue))]));}

  Widget _pmts() => Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('发薪记录',style:TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:AppTheme.textPrimary)),Text('共 ${_payments.length} 条',style:TextStyle(fontSize:12,color:Colors.grey[500]))]),const SizedBox(height:12),_payments.isEmpty?Card(child:Padding(padding:const EdgeInsets.all(32),child:Center(child:Column(children:[Icon(Icons.receipt_long,size:48,color:Colors.grey[300]),const SizedBox(height:8),Text('暂无发薪记录',style:TextStyle(color:Colors.grey[500]))])))):Card(child:Column(children:_payments.map((r){final last=r==_payments.last;return Column(children:[_pi(r),if(!last)const Divider(height:1)]);}).toList()))]));
  Widget _pi(Map<String,dynamic> r){final a=(r['amount'] as num?)?.toDouble()??0;final d=r['date'] as String?;final n=r['note'] as String?;final hi=(r['image_path'] as String?)?.isNotEmpty==true;return ListTile(onTap:()=>_pd(r),leading:Container(padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:Colors.green.withOpacity(0.1),borderRadius:BorderRadius.circular(8)),child:const Icon(Icons.payment,color:Colors.green,size:20)),title:Text(n??'发薪记录',style:const TextStyle(fontSize:14,fontWeight:FontWeight.w500,color:AppTheme.textPrimary)),subtitle:Row(children:[Text(d??'',style:const TextStyle(fontSize:12,color:Colors.grey)),if(hi)...[const SizedBox(width:8),Icon(Icons.image,size:14,color:Colors.grey[400])]]),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text('¥${a.toStringAsFixed(0)}',style:const TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:Colors.green)),const SizedBox(width:4),Icon(Icons.chevron_right,size:18,color:Colors.grey[400])]));}

  void _pd(Map<String,dynamic> r){final a=(r['amount'] as num?)?.toDouble()??0;final d=r['date'] as String? ?? '';final n=r['note'] as String? ?? '无备注';final img=r['image_path'] as String?;showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(ctx)=>DraggableScrollableSheet(initialChildSize:img!=null?0.8:0.5,maxChildSize:0.95,minChildSize:0.3,builder:(ctx,sc)=>Container(decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.only(topLeft:Radius.circular(24),topRight:Radius.circular(24))),child:SingleChildScrollView(controller:sc,child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Center(child:Container(width:40,height:4,decoration:BoxDecoration(color:Colors.grey[300],borderRadius:BorderRadius.circular(2)))),const SizedBox(height:24),Row(children:[Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.green.withOpacity(0.1),shape:BoxShape.circle),child:const Icon(Icons.payment,color:Colors.green,size:28)),const SizedBox(width:16),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('¥${a.toStringAsFixed(0)}',style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold,color:Colors.green)),Text(d,style:const TextStyle(fontSize:14,color:Colors.grey))]))]),const SizedBox(height:24),const Text('备注说明',style:TextStyle(fontSize:14,fontWeight:FontWeight.w500,color:Colors.grey)),const SizedBox(height:8),Container(width:double.infinity,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.grey[100],borderRadius:BorderRadius.circular(12)),child:Text(n,style:const TextStyle(fontSize:15,color:AppTheme.textPrimary))),if(img!=null&&img.isNotEmpty)...[const SizedBox(height:24),const Text('领款单据',style:TextStyle(fontSize:14,fontWeight:FontWeight.w500,color:Colors.grey)),const SizedBox(height:8),GestureDetector(onTap:()=>_fi(img),child:ClipRRect(borderRadius:BorderRadius.circular(12),child:kIsWeb?Image.network(img,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(height:200,color:Colors.grey[200],child:const Center(child:Icon(Icons.broken_image,size:48,color:Colors.grey)))):Image.file(File(img),fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(height:200,color:Colors.grey[200],child:const Center(child:Icon(Icons.broken_image,size:48,color:Colors.grey))))))],const SizedBox(height:24)]))))));}
  void _fi(String img){Navigator.push(context,MaterialPageRoute(builder:(_)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,iconTheme:const IconThemeData(color:Colors.white)),body:Center(child:kIsWeb?Image.network(img,fit:BoxFit.contain):Image.file(File(img),fit:BoxFit.contain)))));}
  Future<void> _deleteWorker() async {final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('确认删除'),content:Text('确定要删除工人 "${widget.worker['name']}" 吗？'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('取消')),TextButton(onPressed:()=>Navigator.pop(ctx,true),style:TextButton.styleFrom(foregroundColor:Colors.red),child:const Text('删除'))]));if(ok==true&&mounted){try{await _db.deleteWorker(_workerId);if(mounted){Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('已删除'),backgroundColor:Colors.green));}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('删除失败: $e'),backgroundColor:Colors.red));}}}
  void _showPay(BuildContext ctx){showModalBottomSheet(context:ctx,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(_)=>_PaymentDialog(workerId:_workerId,workerName:widget.worker['name']??'',owedAmount:_owedSalary,onConfirm:(a,d,n,img)async{try{await _db.insertPayment({'worker_id':_workerId,'amount':double.tryParse(a)??0,'date':d.toIso8601String().split('T').first,'note':n,'image_path':img,'created_at':DateTime.now().toIso8601String()});if(mounted){Navigator.pop(ctx);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('已记录发薪 ¥$a'),backgroundColor:Colors.green));_loadData();}}catch(e){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('保存失败: $e'),backgroundColor:Colors.red));}}));}
}

class _PaymentDialog extends StatefulWidget { final int workerId; final String workerName; final double owedAmount; final Function(String amount,DateTime date,String note,String? imagePath) onConfirm; const _PaymentDialog({required this.workerId,required this.workerName,required this.owedAmount,required this.onConfirm}); @override State<_PaymentDialog> createState() => _PaymentDialogState(); }
class _PaymentDialogState extends State<_PaymentDialog> { final _ac=TextEditingController(),_nc=TextEditingController(); DateTime _sd=DateTime.now(); String? _img; final ImagePicker _pk=ImagePicker(); @override void initState(){super.initState();if(widget.owedAmount>0)_ac.text=widget.owedAmount.toStringAsFixed(0);} @override void dispose(){_ac.dispose();_nc.dispose();super.dispose();}
  Future<void> _cam()async{final i=await _pk.pickImage(source:ImageSource.camera,imageQuality:80);if(i!=null)setState(()=>_img=i.path);}
  Future<void> _gal()async{final i=await _pk.pickImage(source:ImageSource.gallery,imageQuality:80);if(i!=null)setState(()=>_img=i.path);}
  @override Widget build(BuildContext ctx)=>Container(padding:EdgeInsets.only(bottom:MediaQuery.of(ctx).viewInsets.bottom),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.only(topLeft:Radius.circular(24),topRight:Radius.circular(24))),child:SingleChildScrollView(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Center(child:Container(width:40,height:4,decoration:BoxDecoration(color:Colors.grey[300],borderRadius:BorderRadius.circular(2)))),const SizedBox(height:24),Row(children:[const Icon(Icons.payment,color:AppTheme.primaryColor),const SizedBox(width:12),Text('记录发薪 - ${widget.workerName}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold,color:AppTheme.textPrimary))]),const SizedBox(height:24),TextField(controller:_ac,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'发薪金额',prefixText:'¥ ',prefixStyle:const TextStyle(fontSize:18,fontWeight:FontWeight.bold,color:AppTheme.primaryColor),suffixIcon:IconButton(icon:const Icon(Icons.clear),onPressed:()=>_ac.clear()))),const SizedBox(height:16),InkWell(onTap:()async{final p=await showDatePicker(context:ctx,initialDate:_sd,firstDate:DateTime(2020),lastDate:DateTime.now(),locale:const Locale('zh','CN'));if(p!=null)setState(()=>_sd=p);},child:InputDecorator(decoration:const InputDecoration(labelText:'发薪日期',suffixIcon:Icon(Icons.calendar_today)),child:Text(SiteTimeHelper.formatDate(_sd),style:const TextStyle(fontSize:16)))),const SizedBox(height:16),TextField(controller:_nc,maxLines:2,decoration:const InputDecoration(labelText:'备注（可选）',hintText:'例如：3月份工资')),const SizedBox(height:16),Row(children:[const Text('领款单据',style:TextStyle(fontSize:14,color:Colors.grey)),const Spacer(),if(!kIsWeb)...[TextButton.icon(onPressed:_cam,icon:const Icon(Icons.camera_alt,size:18),label:const Text('拍照'))],TextButton.icon(onPressed:_gal,icon:const Icon(Icons.photo,size:18),label:const Text('相册'))]),if(_img!=null)...[const SizedBox(height:8),Stack(children:[ClipRRect(borderRadius:BorderRadius.circular(12),child:kIsWeb?Image.network(_img!,height:120,fit:BoxFit.cover):Image.file(File(_img!),height:120,fit:BoxFit.cover)),Positioned(top:4,right:4,child:GestureDetector(onTap:()=>setState(()=>_img=null),child:Container(padding:const EdgeInsets.all(4),decoration:const BoxDecoration(color:Colors.black54,shape:BoxShape.circle),child:const Icon(Icons.close,color:Colors.white,size:16))))])],const SizedBox(height:24),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>Navigator.pop(ctx),child:const Text('取消'))),const SizedBox(width:16),Expanded(child:ElevatedButton(onPressed:(){if(_ac.text.isEmpty){ScaffoldMessenger.of(ctx).showSnackBar(const SnackBar(content:Text('请输入发薪金额'),backgroundColor:Colors.red));return;}widget.onConfirm(_ac.text,_sd,_nc.text,_img);},child:const Text('确认发薪')))])]))));}
