name: gongdi_app
description: 施工管理 App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  table_calendar: ^3.0.9
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.8.3
  excel: ^4.0.2
  share_plus: ^7.2.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
